#
# JDBC properties
#
spring.datasource.url=jdbc:mysql://localhost:3306/naves_directory
spring.datasource.username=root
spring.datasource.password=admin

# hibernate porque lo investigue y es util y lo queria agregar
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port = 8072
rsa.public-key=classpath:certs/public.pem
rsa.private-key=classpath:certs/private.pem
jwt.ttl-seconds=3600

# configuracion falsa para que el proyecto compile sin errores (no quiero poner mis datos reales lol pero el que este leyendo esto puede configurarlo en su maquina con github oauth2)
spring.security.oauth2.client.registration.github.client-id=TU_CLIENT_ID
spring.security.oauth2.client.registration.github.client-secret=TU_CLIENT_SECRET